# Generated by Django 4.2.7 on 2023-12-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
